version: "3"

services:
  rets-md:
    build: .
    volumes:
      - .:/code
    environment:
      DEV: "true"
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "8080:80"
    volumes:
      - ../aws_server_config/rets-md/proxy/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rets-md
