version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/code
      - ../aws_server_config/retsmd/proxy/conf/nginx.conf:/etc/nginx/conf.d/default.conf
  retsmd:
    image: php:7-fpm-alpine3.7
    environment:
      DEV: "1"
    volumes:
      - .:/code
