version: '3'

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "8080:80"
    volumes:
      - ../aws_server_config/retsmd/proxy/conf/nginx.conf:/etc/nginx/nginx.conf
  retsmd:
    build: .
    environment:
      DEV: "1"
    volumes:
      - .:/code
